# Generated by Django 5.0.4 on 2024-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
        migrations.AlterModelTable(
            name='salary',
            table='salary',
        ),
    ]
