# Generated by Django 5.0.4 on 2024-06-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0002_student_attendance_alter_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
    ]
