# Generated by Django 5.0.4 on 2024-06-23 05:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0003_remove_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_attendances', to='app_attendance.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='app_attendance.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
