# Generated by Django 5.0.4 on 2024-06-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0004_alter_students_address_alter_students_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
