# Generated by Django 5.0.4 on 2024-06-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0006_attendance_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app_attendance.student'),
        ),
    ]
