# Generated by Django 5.0.4 on 2024-06-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0007_student_attendance_alter_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='app_attendance.group'),
            preserve_default=False,
        ),
    ]
