# Generated by Django 5.0.4 on 2024-06-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0008_salary_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
    ]
